// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6gy-EP-EuluTb4gDjYTnuZYTCueld2U',
    appId: '1:789510951855:web:eb390e365b08d69fe7955a',
    messagingSenderId: '789510951855',
    projectId: 'mindfulness-with-nature-2025',
    authDomain: 'mindfulness-with-nature-2025.firebaseapp.com',
    storageBucket: 'mindfulness-with-nature-2025.firebasestorage.app',
    measurementId: 'G-Y5VHMDPF4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdv0kxCdnFNvNjBuVwq87msskdYmKK7P8',
    appId: '1:789510951855:android:9bc2624bfa2540c0e7955a',
    messagingSenderId: '789510951855',
    projectId: 'mindfulness-with-nature-2025',
    storageBucket: 'mindfulness-with-nature-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9f97T7z_mbq8-zTuKF5en2E_V7Ji7dA',
    appId: '1:789510951855:ios:7bf25be1bc8fed13e7955a',
    messagingSenderId: '789510951855',
    projectId: 'mindfulness-with-nature-2025',
    storageBucket: 'mindfulness-with-nature-2025.firebasestorage.app',
    iosBundleId: 'com.example.mindfulnessWithNatureAppFlutter',
  );
}
