name: mindfulness_with_nature_app_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.36
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/